### ISSUE TITLE
A review

### ISSUE THREAD

**Issue by aleos-dev** [shinchik17/tennis-scoreboard#1]
### Generic Exception Handling:
https://github.com/shinchik17/tennis-scoreboard/blob/20ccdabe411a065e9874aed1f9b21cffa3195120/src/main/java/com/alexshin/tennisscoreboard/repository/BaseRepository.java#L16
A better choice would be to catch "HibernateException" rather than the more generic "Exception".

### Transaction Active Check
https://github.com/shinchik17/tennis-scoreboard/blob/20ccdabe411a065e9874aed1f9b21cffa3195120/src/main/java/com/alexshin/tennisscoreboard/repository/BaseRepository.java#L17
It is not sufficient to merely check if the transaction is null; it’s also crucial to verify that the transaction is currently active before attempting a rollback

### Return After Exception
https://github.com/shinchik17/tennis-scoreboard/blob/20ccdabe411a065e9874aed1f9b21cffa3195120/src/main/java/com/alexshin/tennisscoreboard/repository/BaseRepository.java#L22
This should be placed after the commit; there is no reason to return any entity if an exception was thrown.

### Unintentiolan operation possibility
https://github.com/shinchik17/tennis-scoreboard/blob/20ccdabe411a065e9874aed1f9b21cffa3195120/src/main/java/com/alexshin/tennisscoreboard/repository/BaseRepository.java#L41
The update method can perform unintentional operations due to the nature of the merge method. It would be more appropriate to name this method saveOrUpdate, or ensure that the target entity exists in the database.

### Pagination Strategy Issue
https://github.com/shinchik17/tennis-scoreboard/blob/20ccdabe411a065e9874aed1f9b21cffa3195120/src/main/java/com/alexshin/tennisscoreboard/repository/MatchesRepository.java#L12
The current pagination strategy, which relies solely on a static 'start' index, might not yield consistent results in dynamic scenarios where records are frequently added. For instance, adding ten new records during pagination could lead to duplicate results on subsequent pages, particularly with DESC ordering. A more robust solution would involve using a timestamp or other stable identifiers to manage pagination states effectively.

### Unreachable Code
https://github.com/shinchik17/tennis-scoreboard/blob/20ccdabe411a065e9874aed1f9b21cffa3195120/src/main/java/com/alexshin/tennisscoreboard/repository/MatchesRepository.java#L29
This line seems unreachable. Please verify its necessity and correctness in the current implementation.

### Naming Concern
https://github.com/shinchik17/tennis-scoreboard/blob/20ccdabe411a065e9874aed1f9b21cffa3195120/src/main/java/com/alexshin/tennisscoreboard/repository/MatchesRepository.java#L49
The method name handleException may be misleading, as it primarily wraps and rethrows the exception rather than 'handling' it.

## PlayerRepository
https://github.com/shinchik17/tennis-scoreboard/blob/20ccdabe411a065e9874aed1f9b21cffa3195120/src/main/java/com/alexshin/tennisscoreboard/repository/PlayersRepository.java#L16
Ensure consistency in how text case is handled across different repositories. For instance, the MatchRepository converts player names to lowercase, which users might expect to be the same in PlayersRepository. Consider standardizing how text cases are handled across all repositories to avoid confusion and maintain consistent behavior

### OngoingMatchesService
https://github.com/shinchik17/tennis-scoreboard/blob/20ccdabe411a065e9874aed1f9b21cffa3195120/src/main/java/com/alexshin/tennisscoreboard/service/OngoingMatchesService.java#L23
It's great that the method checks for identical player names. However, it appears there’s no check against the list of ongoing matches to prevent a player from participating in multiple matches simultaneously. Since playersRepository.saveOrGet() does not differentiate between players who are already in a match, this could potentially allow the same player to be added to multiple ongoing matches. A possible solution would be to maintain a set of active players and check this set before creating a new match.

#### Dependency management
https://github.com/shinchik17/tennis-scoreboard/blob/20ccdabe411a065e9874aed1f9b21cffa3195120/src/main/java/com/alexshin/tennisscoreboard/servlet/MatchScoreServlet.java#L25
Services are instantiated directly within the servlet, leading to high coupling

#### Logger
https://github.com/shinchik17/tennis-scoreboard/blob/20ccdabe411a065e9874aed1f9b21cffa3195120/src/main/java/com/alexshin/tennisscoreboard/servlet/MatchScoreServlet.java#L40
Once forward() is called, control is transferred to the target resource. If the target page or servlet throws an exception, the servlet container typically handles it according to the error-page configuration in web.xml. Therefore, any code after the forward() call in the original servlet is not executed in cases of runtime errors in the forwarded resource. This could lead to a misunderstanding of the application's behavior during debugging.

## Util declaration
1. Should be final.
2. Should have private constructor.
3. Should throw UnsupportedOperationException() in the private constructor.

I hope this review has offered some insights into potential areas for improvement.

**Comment by shinchik17** [comment]
> ### Transaction Active Check
> https://github.com/shinchik17/tennis-scoreboard/blob/20ccdabe411a065e9874aed1f9b21cffa3195120/src/main/java/com/alexshin/tennisscoreboard/repository/BaseRepository.java#L17
> 
> 
> It is not sufficient to merely check if the transaction is null; it’s also crucial to verify that the transaction is currently active before attempting a rollback

It's sufficient with current Hibernate SessionFactory configuration. I dived into rollback() implementation and that's what I found:

`java
if ( status == TransactionStatus.ROLLED_BACK || status == TransactionStatus.NOT_ACTIVE ) {
			// Allow rollback() calls on completed transactions, just no-op.
			LOG.debug( "rollback() called on an inactive transaction" );
			return;
}`

Rollback() method checks whether transaction is alive or not. That's why I consider that additional check is redundant.

However, if I would like to set "JpaTransactionCompliance" property of SessionFactory to true, I will get IllegalStateException 
in case I try to rollback inactive transaction. 
This is also described inside of rollback() method:

`java
if ( !isActive() ) {
	if ( jpaCompliance.isJpaTransactionComplianceEnabled() ) {
		throw new IllegalStateException(
				"JPA compliance dictates throwing IllegalStateException when #rollback " +
						"is called on non-active transaction" );
	}
}
`
Throwing such exception is describead in JPA specification, but Hibernate doesn't do it by default.
So your suggestion is quite proper for meeting JPA specification requirements. Although assume not so many
people know about this SessionFactory property :)

**Comment by shinchik17** [comment]
> Pagination Strategy Issue
> OngoingMatchesService
As noted in technical task this pet project isn't multiuser that's. So I suppose that these problems lay deeper.

> Dependency management
Do you suggest manually manage with dependency injection?

> Ensure consistency in how text case is handled across different repositories. For instance, the MatchRepository converts player names to lowercase, which users might expect to be the same in PlayersRepository. Consider standardizing how text cases are handled across all repositories to avoid confusion and maintain consistent behavior.  
MatchRepository converts player names to lowercase ONLY in method findByPlayerName(). The reason is implementing 
user-friendly search on /matches page. Player name paraneter converts to lowercase for setting query parameter "name" which is used by SQL operator LIKE.

Agree with all the remaining issues you noted.

**Comment by aleos-dev** [comment]
@shinchik17 
> 
> > Dependency management
> 
> Do you suggest manually manage with dependency injection?


Here are some options you could consider:

- Make all services beloved singletons.
- Since you are already using ServletContextListener, you can use it to initialize your application context and store it in the ServletContext.
- Implement a service locator, which you can use to request the necessary dependencies.

However, if you know what you're doing, simplifying your work shouldn't cause any harm. The choice is yours:)
